- .gitignore
- Makefile
- Tuist/Config.swift
- Tuist/Dependencies.swift
- Tuist/OrganizationName.swift
- Tuist/ProjectDescriptionHelpers/Project+DynamicFramework.swift
- Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
- Workspace.swift
tuist와 makefile을 사용하여 프로젝트의 기본 세팅을 마치었습니다.
> 🔀 :: (#2) 기본 세팅

- Tuist/ProjectDescriptionHelpers/Project+DynamicFramework.swift
- Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
* ProjectDescriptionHelpers/Project+Excutable.swift 수정
* ProjectDescriptionHelpers/Project+DynamicFramework.swift 의 Info.plist의 default값 지정
> 🔀 :: (#10) Info.plist 를 따로 관리할 수 있게 수정

- Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
> 🔀 :: (#12) Project+Excutable에 additionalFiles추가

- Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
> 🔀 :: (#14) Project+Excutable의 Test Target 제거

- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
unit test에 필요한 quick, nimble 설치
> 🔀 :: (#28) install quick,nimble

- .github/workflows/CI.yml
- Makefile
- Tuist/ProjectDescriptionHelpers/SwiftLintScripts.swift
> 🔀 :: (#27) CI

- Modules/RxOfflineCacheModule/Sources/OfflineCacheUtil.swift
- Modules/RxOfflineCacheModule/Tests/OfflineCacheUtilSpec.swift
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
>  test rx offline cache module
> 🔀 :: (#53) test rx offline cache module

- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
> Tuist File 안에 있는 Realm 관련 코드 삭제
- Tuist File Realm 삭제
> 🔀 :: (#69) Realm 흔적 삭제

- Tuist/Dependencies.swift
> 세미콜론 디자인 라이브러리 라이브러리 버전 업데이트
- 트위스트 파일 변경
> 🔀 :: (#74) 세미콜론디자인 라이브러리 버전 업데이트

- Application/Sources/Application/XQUAREApp.swift
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
> 🔀 :: (#82) remove swinject

- Modules/SQLiteModule/Sources/SQLiteTask.swift
> SQLiteModule 변경
- private -> public
- Modules/SQLiteModule/SQLiteTask
> 🔀 :: (#86) SQLiteModule private -> public

- Modules/RestApiModule/Sources/XquareAPI.swift
- Modules/RestApiModule/Tests/RestApiRemoteDataSourceSpec.swift
> 스퀘어 에이피아이 프로퍼티 접근제한을 퍼블릭으로 변경
- public
- Modules/RestApiModule/XquareApi
> 🔀 :: (#91) XQuareApi 프로퍼티 접근제한 public으로 변경

- Application/SupportingFiles/Info.plist
> Delete ApplicationSceneManifest
> 🔀 :: (#88) Delete ApplicationSceneManifest

- Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
> RestApiRemoteDataSource public -> open
- 접근제한 변경
- Modules/RestApiModule/RestApiRemoteDataSource
> 🔀 :: (#94) RestApiRemoteDataSource 접근제한 변경

- Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
> 접근제한 변경
- 접근제한 변경
- Modules/RestApiModule/RestApiDataSource
> 🔀 :: (#96) RestApiRemoteDataSource 접근제한 변경

- Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
> 접근제한 변경 
- RestApiRemoteDataSource 접근제한 변경
- Modules/RestApiModule/RestApiRemoteDataSource
> 🔀 :: (#96) RestApiRemoteDataSource init 접근제한 변경

- Application/SupportingFiles/Info.plist
> 🔀 :: (#100) bundle display name 수정

- Modules/RestApiModule/Sources/DI/RestApiModuleDependcy.swift
> RestApiModule PureDI
- RestApiModule PureDI 설정
- Modules/RestApiModule/RestApiRemoteDataSource
> 🔀 :: (#101) RestApiModule PureDI

- .github/workflows/Testflight.yml
- Modules/RestApiModule/Sources/DI/RestApiModuleDependcy.swift
> 접근제한 변경
- 다른 모듈에서 접근할 수 있도록 접근제한 public으로 변경
- Modules/RestApiModule/RestApiModuleDependency
> 🔀 :: (#111) RestApiModuleDependency 접근제한 변경

- Modules/RxOfflineCacheModule/Sources/OfflineCacheUtil.swift
> RxOfflineCacheModule RxOfflineCacheUtil internal init() -> public init()
- 이니셜라이저 접근제한 변경
- Modules/RxOfflineCacheModule/RxOfflineCacheUtil
> 🔀 :: (#123) internal init -> public init

- Tuist/Dependencies.swift
> 🔀 :: (#130) SD; 버전 업데이트 `1.2.1`

- Tuist/Dependencies.swift
> 🔀 :: (#132) SD; 버전 업데이트 `1.2.2`

- Tuist/Dependencies.swift
> 🔀 :: (#124) SD; 버전 업데이트 `1.2.3`

- Tuist/Dependencies.swift
> 🔀 :: (#136) SD; 버전 업데이트

- Services/MealDataService/Sources/Domain/Entity/DayToMealMenuEntity.swift
- Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuEntity.swift
> MealMenuEntity 접근제한 변경하기
- MealMenuEntity property internal -> public 
- Services/MealDataService/**
> 🔀 :: (#140) MealMenuEntity 접근제한 public으로 변경

- Services/MealDataService/Sources/Domain/UseCase/FetchDayToMealMenuUseCase.swift
- Services/MealDataService/Sources/Domain/UseCase/FetchMonthToMealMenuUseCase.swift
> UseCase excute 메소드 접근제한 변경
- UseCase excute 메소드 public으로 접근제한 변경
- Services/MealDataService/Domain/UseCase/**
> 🔀 :: (#142) MealDataService UseCase 접근제한 public으로 변경하기

- Application/Sources/Scene/Home/Meal/MealListCell.swift
- Application/Sources/Scene/Home/Meal/MealMenuView.swift
- Application/Sources/Scene/Home/Profile/ProfileView.swift
- Application/Sources/Scene/Main/MainView.swift
- Tuist/Dependencies.swift
> 🔀 :: (#144) SD; 1.5.0 업데이트 및 대응

- Application/SupportingFiles/Info.plist
> 🔀 :: (#147) 라이트 모드 고정

- Application/Sources/Scene/Main/MainView.swift
> 🔀 :: (#138) TabView AccentColor 지정

- Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
> 접근제한 변경하기 
- MonthtoMealMenuRequestEntity internal -> public으로 변경
- Services/MealDataService/Domain/RequestEntity
> 🔀 :: (#149) MealDataService 접근제한 변경하기

- Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
> 이니셜라이저 접근제한 변경 및 초기화 코드 작성
- RequestEntity init -> public init
- Services/MealDataService/Domain/Entity
> 🔀 :: (#151) MealDataService RequestEntity 이니셜라이저 접근제한 변경

- Application/Project.swift
- Modules/XWebKit/Project.swift
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
> setting XWebView
insatall RxWebView
> 🔀 :: (#156) setting XWebView

- Services/MealDataService/Sources/Domain/Enum/MealTime.swift
> mealTimeOrder 추가하기
- MealDataService MealTime에 mealTimeOrder 추가
- MelaDataService/Domain/Enum/MealTime
> 🔀 :: (#162) MealDataService MealTime + mealTimeOrder

- Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSource.swift
- Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
- Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
- Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSource.swift
- Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSourceImpl.swift
- Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerDayResponse.swift
- Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthListResponse.swift
- Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthResponse.swift
- Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
- Services/MealDataService/Sources/Domain/Entity/MealMenuEntity.swift
- Services/MealDataService/Sources/Domain/Entity/MealMenuPerDayEntity.swift
- Services/MealDataService/Sources/Domain/Repository/MealRepository.swift
- Services/MealDataService/Sources/Domain/UseCase/FetchMealMenuPerDayUseCase.swift
- Services/MealDataService/Sources/Domain/UseCase/FetchMealMenuPerMonthUseCase.swift
> MealMenuEntity 추가 및 변경
- MealMenuEntity 수정
- MealMenuPerDayEntity 추가
- Services/MealDataService/Source/Domain/Entity
> 🔀 :: (#165) MealMenuEntity 추가 및 변경

- Tuist/Dependencies.swift
> 🔀 :: (#167) Update SD; to 1.6.0

- Tuist/Dependencies.swift
> SD-Version 1.6.0 -> 1.7.0으로 변경
- SD Version 변경
> 🔀 :: (#169) SD-Version Update

- Modules/XNavigationLink/Project.swift
- Modules/XNavigationLink/Sources/XNavigationLinkWithoutTabbar.swift
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
> 🔀 :: (#176) XNavigationLink 개발

- Modules/XNavigationLink/Sources/OnChangePresentationMode.swift
- Modules/XNavigationLink/Sources/XNavigationLinkWithoutTabbar.swift
- Modules/XWebKit/Sources/XWebKitView.swift
> 🔀 :: (#179) 탭바 버그 수정

- Services/AuthService/Sources/Domain/Entity/SigninEntity.swift
- Services/AuthService/Sources/Domain/Entity/SignupEntity.swift
> AuthService Request 이니셜라이저를 Public으로 설정합니다.
> 🔀 :: (#190) Request init 접근제한 변경

- Tuist/Dependencies.swift
> 🔀 :: (#193) SD-Version-Update

- Tuist/Dependencies.swift
> 🔀 :: (#198) SD 업데이트

- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Home/HomeViewModel.swift
- Application/Sources/Scene/Home/Meal/MealListCell.swift
- Application/Sources/Scene/Home/Meal/MealMenuView.swift
- Application/Sources/Scene/Home/Profile/ProfileView.swift
> 보이지 않는 급식 버그 해결
> 근본적으로 서브뷰들들에 프로퍼티를 `@State`를 달아놔서 값 연동이 안됐었음
- 코드 정리
- 버그 해결
- 서브뷰 프로퍼티에 `@State` 제거
> 🔀 (#192) 보이지 않는 급식 버그 해결

- Application/Sources/Scene/Application/ApplicationView.swift
- Application/Sources/Scene/Entire/EntireView.swift
- Application/Sources/Scene/Feed/FeedView.swift
- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Main/MainView.swift
- Application/Sources/Scene/Schedule/ScheduleView.swift
- Modules/XNavigationAndTab/Sources/XNavigationAndTabContent.swift
- Modules/XWebKit/Sources/XWebKitState.swift
- Modules/XWebKit/Sources/XWebKitView.swift
> 이제 Navigation안에 Tab이 있는 구조가 됨 -> 불편했던 UI개선
> 🔀 :: (#206) XNavigationAndTab 업데이트 대응

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Login/LoginView.swift
- Application/Sources/Scene/Login/LoginViewModel.swift
- Application/Sources/Scene/SignUp/SignUpView.swift
- Services/AuthService/Sources/Data/Remote/Response/SigninAndRefreshTokenResponse.swift
> LoginViewModel을 LoginView에 연동합니다.
> 🔀 :: (#188) LoginViewModel 연동하기

- Modules/RestApiModule/Sources/XquareAPI.swift
- Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
> 🔀 :: (#210) [임시] 서버 교체

- Application/Sources/Scene/Login/LoginViewModel.swift
- Application/SupportingFiles/Info.plist
> 로그인시 디바이스 토큰 전송
추가로 로그뜨던 FirebaseAppDelegateProxyEnabled 관련 문제 해결
ㄴ 에널리틱스 같은거 안쓰면 false로 해야함
> 🔀 :: (#217) send device token when login

- Application/Sources/Scene/Signup/SignupViewModel.swift
- Services/AuthService/Sources/Data/Remote/Request/SignupRequest.swift
- Services/AuthService/Sources/Domain/Entity/SignupEntity.swift
> 🔀 :: (#216) 회원가입 에러 해결

- Modules/XWebKit/Sources/XWebKitProgressViewStyle.swift
> 🔀 :: (#221) 보라맛 UI 버그 해결

- Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
- Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
- Modules/XWebKit/Sources/XWebKitState.swift
- Modules/XWebKit/Sources/XWebKitView.swift
> 🔀 :: (#174) send token to webview

- Services/AuthService/Sources/DI/AuthServiceDependency.swift
- Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
- Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
- Services/AuthService/Sources/Domain/UseCase/FetchAccessTokenUseCase.swift
> 🔀 :: (#226) FetchAccessTokenUseCase

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Application/ApplicationView.swift
- Application/Sources/Scene/Application/ApplicationViewModel.swift
> 🔀 :: (#227) 신청 페이지 webview 연동

- Modules/DateUtilModule/Sources/DateFormat.swift
- Modules/DateUtilModule/Sources/DateToString.swift
- Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
- Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
> #236 을 기반으로 포멧을 추가하려했지만 앞으로 포멧이 추가될때마다 모듈을 수정할 순 없기에 string format으로 String으로 바꿔주는 Date Extension 메서드 구현.
추가적으로 오타와 수정을 했고 해당 수정의 사이드 이펙트도 함께 수정했습니다.
> 🔀 :: (#236) add date to string method with string format

- Tuist/ProjectDescriptionHelpers/Project Frame/Project+Excutable.swift
> 로그창을 더렵혔던 시스템 로그들을 비활성화시켰습니다.
> 🔀 :: (#234) disable OS_ACTIVITY_MODE

- Modules/DateUtilModule/Sources/DateToString.swift
> 🔀 :: (#239) Date Local 한국으로 지정하기

- Services/MealDataService/Sources/Domain/Entity/MealMenuPerDayEntity.swift
> MealMenuPerDayEntity 이니셜라이저 퍼블릭으로 변경합니다.
> 🔀 :: (#240) MealMenuPerDayEntity 이니셜라이저 퍼블릭으로 변경

- Modules/XWebKit/Project.swift
- Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
- Modules/XWebKit/Sources/RxWebKit/EstimatedProgress.swift
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
> xcode14에서 일어나는 'Type of expression is ambiguous without more context' 에러 해결
- RxWebKit에서 필요한 부분의 코드만 추출하여 사용하게 하였다.
> 🔀 :: (#247) xcode14 rx web kit error

- Tuist/Dependencies.swift
> 🔀 :: (#245) remove Introspect on SPM

- Modules/RestApiModule/Project.swift
- Modules/RestApiModule/Sources/XquareAPI.swift
- Modules/XEnvironment/Project.swift
- Modules/XEnvironment/Sources/XEnvironment.swift
- Modules/XEnvironment/SupportingFiles/Info.plist
- Services/AuthService/Project.swift
- Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
> xcconfig에 작성한 환경변수를 쉽게 가져와 사용할 수 있게하는 모듈을 개발하고 당장에 필요한 AuthService와 ResrApiModule에 적용하였습니다.
> 🔀 :: (#253) XEnvironment 모듈 개발 및 적용

- Application/Project.swift
- Application/Widget/SupportingFiles/Info.plist
> 직접적으로 info.plist가 없어 CD에서 버전을 세팅해주지 못하는 이슈때문에 info.plist를 직접 만들어 세팅하였습니다.
> 🔀 :: (#260) widget Info.plist 추가

- Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
- Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
- Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
> 🔀 :: (#263) MealMenu kcal오류 해결

- Application/SupportingFiles/Info.plist
> 앱스토어에서 매번 체크를 해주었어야 했던 항목을 생략할 수 있게끔 세팅하였습니다.
> 🔀 :: (#269) App Uses Non-Exempt Encryption 세팅

- Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
> 🔀 :: (#273) 필요없는 것들들 삭제

- Services/UserService/Project.swift
- Services/UserService/Sources/Data/Remote/API/UserAPI.swift
- Services/UserService/Sources/Data/Remote/DataSource/RemotaUserDataSource.swift
- Services/UserService/Sources/Data/Remote/DataSource/RemoteUserDataSourceImpl.swift
- Services/UserService/Sources/Data/Remote/Repository/UserRepositoryImpl.swift
- Services/UserService/Sources/Data/Remote/Response/UserResponse.swift
- Services/UserService/Sources/Domain/Repository/UserRepository.swift
- Services/UserService/Sources/Domain/UseCase/FetchUserPointUseCase.swift
> 유저서비스에 에러와 명세에 맞게 수정합니다.
- tuist 오타 수정
- 유저서비스 fetchUserPoint api 파라미터 삭제
> 🔀 :: (#285) 유저서비스 에러 및 수정

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Home/HomeView.swift
- Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
- Services/MealDataService/Project.swift
- Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
- Services/UserService/Sources/DI/UserServiceDependency.swift
> 특히 각 서비스에서 직접 생성하여 주입하던 AuthServiceDependency 주입형으로 변경
> 🔀 :: (#279) RestApiModule 관련 의존성 정리

- Application/Project.swift
> DEV scheme에서 시스템로그 비활성화
이거 하고나니 보라맛 에러들도 다 없어짐..
> 🔀 :: (#234) DEV scheme에서 시스템로그 비활성화

- Modules/KeychainModule/Sources/KeychainModule.swift
> 🔀 :: (#215) KeychainModule 주석 수정

- Application/Project.swift
- Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/Contents.json
- Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/Contents.json
- Application/Sources/Application/AppDependency.swift
- Modules/KeychainModule/Project.swift
- Modules/RestApiModule/Project.swift
- Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
- Modules/RxOfflineCacheModule/Project.swift
- Modules/XDateUtil/Project.swift
- Modules/XEnvironment/Project.swift
- Modules/XNavigationAndTab/Project.swift
- Modules/XWebKit/Project.swift
- Services/AuthService/Project.swift
- Services/AuthService/Sources/DI/AuthServiceDependency.swift
- Services/MealDataService/Project.swift
- Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
- Services/UserService/Project.swift
- Services/UserService/Sources/DI/UserServiceDependency.swift
- Tuist/ProjectDescriptionHelpers/Project Frame/Project+Framework.swift
> 서비스들의 Dependency를 싱글톤으로 바꿈으로서 프로젝트 구조를 개편하였고
추가로 tuist도 수정했습니다.
> 🔀 :: (#302, #303) 프로젝트 구조 개편

- Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
- Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
- Modules/XWebKit/Sources/XWebKitState.swift
- Modules/XWebKit/Sources/XWebKitView.swift
> 에러 브릿지를 추가하고 SDErrorAlert과 연동하였습니다.
> 🔀 :: (#301) XWebKit add error bridge

- Modules/XDateUtil/Sources/DateFormat.swift
> 🔀 :: (#320) fullDateWithTime DateFormat 수정

- Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
- Modules/XWebKit/Sources/XWebKitState.swift
- Modules/XWebKit/Sources/XWebKitView.swift
> XWebKit navigate bridge 변경 대응
> 🔀 :: (#329) XWebKit navigate bridge 변경 대응

- Application/Sources/Scene/MealDetail/MealDetailView.swift
- Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
> 🔀 :: (#333) 오늘 급식부터 보여주기

- Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
> 🔀 :: (#335) XWebKit 토큰에 "Bearer" 추가

- Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
> 🔀 :: (#338) 웹뷰 토큰 방식 쿠키로 변경

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Entire/EntireView.swift
- Application/Sources/Scene/Entire/TopServiceMenu/TopServiceMenuView.swift
- Application/Sources/Scene/PointHistory/PointHistoryListCellView.swift
- Application/Sources/Scene/PointHistory/PointHistoryView.swift
- Application/Sources/Scene/PointHistory/SelectButtonView.swift
> 🔀 :: (#346) point history UI

- Application/Project.swift
- Services/AttachmentService/Project.swift
- Services/AttachmentService/Sources/DI/AttachmentServiceDependency.swift
- Services/AttachmentService/Sources/Data/Remote/API/AttachmentAPI.swift
- Services/AttachmentService/Sources/Data/Remote/DataSource/RemoteAttachmentDataSource.swift
- Services/AttachmentService/Sources/Data/Remote/DataSource/RemoteAttachmentDataSourceImpl.swift
- Services/AttachmentService/Sources/Data/Remote/Response/ImageUrlResponse.swift
- Services/AttachmentService/Sources/Data/Repository/AttachmentRepositoryImpl.swift
- Services/AttachmentService/Sources/Domain/Repository/AttachmentRepository.swift
- Services/AttachmentService/Sources/Domain/UseCase/UploadImageUseCase.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
> 🔀 :: (#367) AttachmentDataService

- Modules/XWebKit/Project.swift
- Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
- Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
- Modules/XWebKit/Sources/XWebKitState.swift
- Modules/XWebKit/Sources/XWebKitView.swift
> 🔀 :: (#341) XWebKit에 photo picker 브릿지 추가

- Application/Sources/Extension/UINavigationController.swift
> 🔀 :: (#372) SwipeBack

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Login/LoginView.swift
- Application/Sources/Scene/Login/LoginViewModel.swift
- Application/SupportingFiles/Info.plist
- Services/AuthService/Sources/DI/AuthServiceDependency.swift
- Services/AuthService/Sources/Data/Local/DataSource/LocalAuthDataSource.swift
- Services/AuthService/Sources/Data/Local/DataSource/LocalAuthDataSourceImpl.swift
- Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
- Services/AuthService/Sources/Domain/Entity/IdAndPasswordEntity.swift
- Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
- Services/AuthService/Sources/Domain/UseCase/AutoLoginUseCase.swift
- Services/AuthService/Sources/Domain/UseCase/FetchIdAndPasswordUseCase.swift
> 자동 로그인을 구현합니다.
faceId를 성공하면 id와 password를 넣어주고 알아서 로그인까지 진행됩니다.
> 🔀 :: (#351) FaceID를 통한 자동 로그인

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/BugReport/BugReportView.swift
- Application/Sources/Scene/BugReport/BugReportViewModel.swift
- Application/Sources/Scene/BugReport/DropDown/DropDown.swift
- Application/Sources/Scene/BugReport/DropDown/DropDownRow.swift
- Application/Sources/Scene/BugReport/DropDown/DropDownSelector.swift
- Application/Sources/Scene/BugReport/ImportantText/ImportantTextView.swift
- Application/Sources/Scene/Entire/EntireView.swift
- Application/Sources/Scene/Entire/TopServiceMenu/TopServiceMenuView.swift
- Tuist/Dependencies.swift
> 🔀 :: (#383) 버그 신고 화면 퍼블리싱

- Services/TimeTableService/Project.swift
- Services/TimeTableService/Sources/DI/TimeTableServiceDependency.swift
- Services/TimeTableService/Sources/Data/Remote/API/TimeTableAPI.swift
- Services/TimeTableService/Sources/Data/Remote/DataSource/RemoteTimeTableDataSource.swift
- Services/TimeTableService/Sources/Data/Remote/DataSource/RemoteTimeTableDataSourceImpl.swift
- Services/TimeTableService/Sources/Data/Remote/Repository/TimeTableRepositoryImpl.swift
- Services/TimeTableService/Sources/Data/Remote/Response/DayTimeTableResponse.swift
- Services/TimeTableService/Sources/Data/Remote/Response/WeekTimeTableListResponse.swift
- Services/TimeTableService/Sources/Data/Remote/Response/WeekTimeTableResponse.swift
- Services/TimeTableService/Sources/Domain/Entity/DayTimeTableEntity.swift
- Services/TimeTableService/Sources/Domain/Entity/WeekTimeTableEntity.swift
- Services/TimeTableService/Sources/Domain/Error/TimeTableServiceError.swift
- Services/TimeTableService/Sources/Domain/Repository/TimeTableRepository.swift
- Services/TimeTableService/Sources/Domain/UseCase/FetchTimeTableForWeekUseCase.swift
> TimeTableService를 작성합니다.
> TimeTableService를 작성합니다.
> 🔀 :: (#386) TimeTableService 작성

- Application/Project.swift
- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
- Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleViewModel.swift
- Application/Sources/Scene/Schedule/AcademicSchedule/Cell/AcademicScheduleCell.swift
- Application/Sources/Scene/Schedule/Button/ScheduleButtonView.swift
- Application/Sources/Scene/Schedule/ScheduleView.swift
- Application/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCell.swift
- Application/Sources/Scene/Schedule/TimeTable/PageControl/PageControlView.swift
- Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
- Application/Sources/Scene/Schedule/TimeTable/TimeTableViewModel.swift
- Application/Sources/Scene/WriteSchedule/WriteScheduleView.swift
- Application/Sources/Scene/WriteSchedule/WriteScheduleViewModel.swift
- Modules/XDateUtil/Sources/DateFormat.swift
- Services/ScheduleService/Sources/DI/ScheduleServiceDependency.swift
- Services/ScheduleService/Sources/Data/Remote/API/ScheduleAPI.swift
- Services/ScheduleService/Sources/Data/Remote/Response/ScheduleResponse.swift
- Services/ScheduleService/Sources/Domain/Entity/ScheduleEntity.swift
- Services/ScheduleService/Sources/Domain/UseCase/FetchScheduleForMonthUseCase.swift
- Services/ScheduleService/Sources/Domain/UseCase/FetchSchedulePerMonthUseCase.swift
- Services/TimeTableService/Sources/Data/Remote/Response/DayTimeTableResponse.swift
- Services/TimeTableService/Sources/Data/Remote/Response/WeekTimeTableResponse.swift
- Services/TimeTableService/Sources/Domain/Entity/DayTimeTableEntity.swift
- Services/TimeTableService/Sources/Domain/Entity/WeekTimeTableEntity.swift
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
> 일정 화면 기능을 구현합니다.
- 일정 화면 퍼블리싱
- 일정 화면 api 연동
-
> 🔀 :: (#384) 일정 화면 퍼블리싱 및 api 연동

- Application/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCell.swift
- Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
- Tuist/Dependencies.swift
> 🔀 :: (#391) Remove PageControl

- Tuist/Dependencies.swift
> 🔀 :: (#402) 세미콜론 디자인 버전 업데이트

- Application/Sources/Scene/BugReport/DropDown/DropDownSelector.swift
- Application/Sources/Scene/Login/LoginView.swift
- Application/Sources/Scene/Login/LoginViewModel.swift
- Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
- Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
- Application/Sources/Scene/WriteSchedule/WriteScheduleViewModel.swift
- Application/SupportingFiles/Info.plist
- Tuist/Dependencies.swift
> 앱 크러쉬 나는 요소들을 삭제하고 수정합니다.
- FaceID는 삭제함.
- Calendar 버튼 크기 늘림
- TimePicker 에러 고치고 세미콜론 버전 업데이트
> 🔀 :: (#404) App Crash

- Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
- Tuist/Dependencies.swift
> Keyboard로 인해서 TabView가 올라가는 버그 고침
> 🔀 :: (#407) Keyboard로 인해서 TabView가 올라가는 버그 고침

- Application/Widget/Sources/Meal/XquareMealWidget.swift
- Application/Widget/Sources/Schedule/ScheduleWidgetCell.swift
- Application/Widget/Sources/Schedule/XquareScheduleWidget.swift
> 🔀 :: (#423) Widget 다크모드 대응

- Services/NotificationService/Project.swift
- Services/NotificationService/Sources/DI/NotificationServiceDependency.swift
- Services/NotificationService/Sources/Data/Remote/API/NotificationAPI.swift
- Services/NotificationService/Sources/Data/Remote/DataSource/RemoteNotificationDataSource.swift
- Services/NotificationService/Sources/Data/Remote/DataSource/RemoteNotificationDataSourceImpl.swift
- Services/NotificationService/Sources/Data/Remote/Repository/NotificationRepositoryImpl.swift
- Services/NotificationService/Sources/Data/Remote/Response/CategoryListResponse.swift
- Services/NotificationService/Sources/Data/Remote/Response/CategoryResponse.swift
- Services/NotificationService/Sources/Data/Remote/Response/NotificationListResponse.swift
- Services/NotificationService/Sources/Data/Remote/Response/NotificationResponse.swift
- Services/NotificationService/Sources/Data/Remote/Response/UnreadCountResponse.swift
- Services/NotificationService/Sources/Domain/Entity/CategoryEntity.swift
- Services/NotificationService/Sources/Domain/Entity/NotificationEntity.swift
- Services/NotificationService/Sources/Domain/Error/NotificationServiceError.swift
- Services/NotificationService/Sources/Domain/Repository/NotificationRepository.swift
- Services/NotificationService/Sources/Domain/UseCase/ActiveNotificationCategoryUseCase.swift
- Services/NotificationService/Sources/Domain/UseCase/CheckNotificationUseCase.swift
- Services/NotificationService/Sources/Domain/UseCase/FetchActivatedCategoryListUseCase.swift
- Services/NotificationService/Sources/Domain/UseCase/FetchNotificationCategoryListUseCase.swift
- Services/NotificationService/Sources/Domain/UseCase/FetchPostedNotificationListUseCase.swift
- Services/NotificationService/Sources/Domain/UseCase/FetchUncheckNotificationCountUseCase.swift
- Services/NotificationService/Sources/Domain/UseCase/InactiveNotifcationCategoryUseCase.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
> 🔀 :: (#430) NotificationService

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
- Application/Sources/Scene/Notification/NotificationView.swift
> 🔀 :: (#425) NotificationView

- Services/PickService/Project.swift
- Services/PickService/Sources/DI/PickServiceDependency.swift
- Services/PickService/Sources/Data/Remote/API/PickAPI.swift
- Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSource.swift
- Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSourceImpl.swift
- Services/PickService/Sources/Data/Remote/Repostitory/PickRepositoryImpl.swift
- Services/PickService/Sources/Data/Remote/Response/MovedClassResponse.swift
- Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
- Services/PickService/Sources/Data/Remote/Response/OutingReturnTimeResponse.swift
- Services/PickService/Sources/Domain/Entity/MovedClassEntity.swift
- Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
- Services/PickService/Sources/Domain/Entity/OutingReturnTimeEntity.swift
- Services/PickService/Sources/Domain/Error/PickServiceError.swift
- Services/PickService/Sources/Domain/Repository/PickRepository.swift
- Services/PickService/Sources/Domain/UseCase/DeleteReturnClassUseCase.swift
- Services/PickService/Sources/Domain/UseCase/FetchMovedClassUseCase.swift
- Services/PickService/Sources/Domain/UseCase/FetchOutingPassUseCase.swift
- Services/PickService/Sources/Domain/UseCase/FetchOutingReturnTimeUseCase.swift
- Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
> 🔀 :: (#427) PickService

- Application/Sources/Scene/Login/LoginView.swift
- Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
- Application/Sources/Scene/Signup/SignupView.swift
- Tuist/Dependencies.swift
> 🔀 :: (#435) SDErrorAlert -> SDOkayAlert

- Application/Project.swift
- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Home/HomeViewModel.swift
- Application/Sources/Scene/Home/MovedClass/ClassRoomMoveView.swift
- Application/Sources/Scene/Home/Outing/OutingView.swift
- Application/Sources/Scene/OutingPass/Animation/SlidingTextView.swift
- Application/Sources/Scene/OutingPass/Information/OutingInformationView.swift
- Application/Sources/Scene/OutingPass/OutingPassView.swift
- Application/Sources/Scene/OutingPass/OutingPassViewModel.swift
- Modules/XDateUtil/Sources/StringToDate.swift
- Services/PickService/Sources/DI/PickServiceDependency.swift
- Services/PickService/Sources/Data/Remote/API/PickAPI.swift
- Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSourceImpl.swift
- Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
- Services/PickService/Sources/Data/Remote/Response/OutingReturnTimeResponse.swift
- Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
- Services/TimeTableService/Sources/Data/Remote/Response/DayTimeTableResponse.swift
> 픽 기능 뷰 퍼블리싱
- 외출증 뷰 구현
- 외출증 api 연동
close #428
> 🔀 :: (#428) PickView publishing

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/Application/ApplicationView.swift
- Application/Sources/Scene/Application/ApplicationViewModel.swift
- Application/Sources/Scene/Feed/FeedView.swift
- Application/Sources/Scene/Feed/FeedViewModel.swift
- Services/AuthService/Sources/DI/AuthServiceDependency.swift
- Services/AuthService/Sources/Domain/UseCase/RefreshTokenIfExpiredUseCase.swift
- Tuist/Dependencies.swift
> 토큰 만료시 웹뷰 작동안하는 문제 해결:
웹뷰 페이지 접근시 토큰 만료상태면 재발급, 새로고침시 토큰 최신 토큰 가져오도록 수정
- XWebKit update
- RefreshTokenIfExpiredUseCase 작성
- 웹뷰 페이지 접근시 토큰 만료상태면 재발급, 새로고침시 토큰 최신 토큰 가져오도록 수정
> 🔀 :: (#438) XWebKit update & 웹뷰 토큰 플로우 설계

- Application/Widget/Sources/Meal/XquareMealWidget.swift
> 🔀 :: (#441) MealWidget Bug

- Application/Sources/Application/AppDependency.swift
- Application/Sources/Scene/OutingPass/OutingPassView.swift
- Application/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCell.swift
- Application/Sources/Scene/Schedule/TimeTable/TimeTableViewModel.swift
- Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
- Services/PickService/Sources/DI/PickServiceDependency.swift
- Services/PickService/Sources/Data/Remote/API/PickAPI.swift
- Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSource.swift
- Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSourceImpl.swift
- Services/PickService/Sources/Data/Remote/Repostitory/PickRepositoryImpl.swift
- Services/PickService/Sources/Data/Remote/Response/TodaySelfStudyTeacherListResponse.swift
- Services/PickService/Sources/Data/Remote/Response/TodaySelfStudyTeacherResponse.swift
- Services/PickService/Sources/Domain/Entity/TodaySelfStudyTeacherEntity.swift
- Services/PickService/Sources/Domain/Entity/TodaySelfStudyTeacherListEntity.swift
- Services/PickService/Sources/Domain/Repository/PickRepository.swift
- Services/PickService/Sources/Domain/UseCase/FetchTodaySelfStudyTeacherUseCase.swift
- Services/ScheduleService/Sources/Data/Remote/Repository/ScheduleRepositoryImpl.swift
> 자습시간 선생님 조회 서비스 구현
- Pick 명세 참고해서 API 구현
close #447
> 🔀 :: (#447) TodaySelfStudyTeacher Service

- Application/Sources/Scene/Login/LoginView.swift
> id,비번 찾기 버튼 눌렀을때 페이스북으로 넘어가게 하기
- 아이디/비밀번호 누르면 페이스북으로 넘기기
https://user-images.githubusercontent.com/80248855/232804457-896885f4-b1d3-42eb-8e1f-4825b7cac625.mov
> 🔀 :: (#459) chage id password to faceBook

- Application/Sources/Scene/Entire/EntireView.swift
- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Login/LoginView.swift
- Application/Sources/Scene/Main/MainView.swift
- Modules/XDateUtil/Sources/DateToString.swift
- Modules/XDateUtil/Sources/StringToDate.swift
- Modules/XDateUtil/Sources/XDateFormatter.swift
> 버그 수정
- 뷰 이동시 todate()로 인해 터지는거 오류 수정 & 전체뷰에서 back했을때 홈뷰로 넣어가는거 수정
- 
https://user-images.githubusercontent.com/103028061/232823193-27dd1452-384c-4f5e-81c9-e4badd7279bd.mp4
> 🔀 :: (#462) ReleaseBugFix

- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Home/HomeViewModel.swift
> PickService 주석해제
- PickService 주석해제
-
> 🔀 :: (#469) PickService 주석해제

- Application/Sources/Router/XQUARE/XquareRouterFactory.swift
- Application/Sources/Scene/MyPage/MyPageView.swift
- Application/Sources/Scene/MyPage/MyPageViewModel.swift
> 🔀 :: (#473) withdrawal

- Application/Sources/Scene/Entire/EntireView.swift
- Application/Sources/Scene/MyPage/MyPageView.swift
>  로그아웃 네 아니요 버튼 위치 변경
- 
- 
https://user-images.githubusercontent.com/103028061/235922016-1d856183-f0d8-4758-9803-9f76036a6aca.mp4
> 🔀 :: (#476) 로그아웃 네 아니요 버튼 위치 변경

- Application/Sources/Scene/EditSchedule/EditScheduleView.swift
- Application/Sources/Scene/Signup/SignupView.swift
- Application/Sources/Scene/WriteSchedule/WriteScheduleView.swift
- Tuist/Dependencies.swift
> SemicolonDesign_iOS 버전 업
- SDTextField isImportant 추가
- SemicolonDesign_iOS 버전 업
-
> 🔀 :: (#478) SemicolonDesign_iOS 버전 업

- Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
> SwiftLint 업데이트로 인한 버그 수정
- Task의 try-catch 작성
close #487
> 🔀 :: (#487) fix SwiftLint Bug

- Application/Sources/Scene/Home/Meal/MealListCell.swift
- Application/Sources/Scene/Home/Meal/MealMenuView.swift
- Application/Sources/Scene/MealDetail/Cell/MealMenuPerMealTimeView.swift
- Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
- Services/MealDataService/Sources/Domain/Enum/MealTime.swift
> 급식 디자인 수정
- 급식 셀 디자인 수정
- 급식 셀 클릭 범위 조정
close #481
> 🔀 :: (#481) Change Meal Design

- Application/Sources/Scene/OutingPass/Animation/SlidingTextView.swift
- Application/Sources/Scene/OutingPass/Information/OutingInformationView.swift
- Application/Sources/Scene/OutingPass/OutingPassView.swift
- Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
- Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
> 외출증 폰트 수정 및 외출날짜 추가
- 디자인에 맞게 외출증 간격 조정
- 학생들 요구사항에 맞게 외출 날짜 추가
- 지킴이 선생님 요구사항에 맞게 전체적인 폰트크기 키우기
- 
https://github.com/team-xquare/xquare-iOS/assets/103028061/b5ca884d-9d03-4d90-a7f9-a5fef14edc74
> 🔀 :: (#486) 외출증 폰트 수정 및 외출날짜 추가

- Application/Sources/Scene/Home/Meal/MealMenuView.swift
> 시간에 따라 급식 스크롤 포커싱처리
- 시간에 따라 급식 스크롤 포커싱처리
- 
https://github.com/team-xquare/xquare-iOS/assets/103028061/b8b31456-c5ee-4424-946a-1ef03c7f501e
> 🔀 :: (#495) 시간에 따라 급식 스크롤 포커싱처리

- Application/Sources/Scene/Home/HomeView.swift
- Application/Sources/Scene/Home/HomeViewModel.swift
- Application/Sources/Scene/OutingPass/OutingPassView.swift
- Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
- Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
> 외출증 디테일 뷰에서 사진값이 null일때 값을 못받아오는 버그 수정
- OutingPassResponse와 OutingPassEntity의 profileFileName에 옵셔널 처리
- OutingPassView에 옵셔널 대응
close #500
> 🔀 :: (#500) fix outing pass bug

- Services/AuthService/Sources/DI/AuthServiceDependency.swift
- Services/AuthService/Sources/Data/Local/DataSource/LocalTokenDataSource.swift
- Services/AuthService/Sources/Data/Local/DataSource/LocalTokenDataSourceImpl.swift
- Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
- Services/AuthService/Sources/Plugin/JWTPulgin.swift
> Local 오타 수정
- Loacl -> Local
> 🔀 :: (#505) Local 오타 수정

- Application/Sources/Scene/Home/Meal/MealListCell.swift
- Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
- Application/Sources/Scene/PointHistory/PointHistoryListCellView.swift
- Application/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCell.swift
- Application/Sources/Scene/Setting/ToggleCell/ToggleView.swift
- Application/Sources/Scene/Signup/TermsCaptionView.swift
- Application/Widget/Sources/Meal/XquareMealWidget.swift
- Application/Widget/Sources/Schedule/ScheduleWidgetCell.swift
- Application/Widget/Sources/Schedule/XquareScheduleWidget.swift
- Tuist/Dependencies.swift
> semicolon design version up
- semicolon design version up
-
> 🔀 :: (#514) semicolon design version up

- Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/Contents.json
- Application/Sources/Scene/ReleaseNote/Cell/ReleaseNoteCellView.swift
> 릴리즈 노트 뷰 버그 수정
- 패딩 조정
close #508
> 🔀 :: (#508) fix release bug

- Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
- Services/NotificationService/Sources/Domain/Enum/NotificationTopic.swift
> notification feed category 추가
- notification feed category 추가
> 🔀 :: (#510) notification feed category 추가

- Application/Sources/Scene/Home/HomeViewModel.swift
> 홈 탭바 누를때마다 급식 포커싱 처리 
- 홈 탭바 누를때마다 급식 포커싱 처리 
https://github.com/team-xquare/xquare-iOS/assets/103028061/1df263b7-1d2b-48c3-963e-e086025e8099
> 🔀 :: (#518) 홈 탭바 누를때마다 급식 포커싱 처리 

- Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
> 하단 탭바에 햅틱반응 추가하였습니다.
+ 약간의 코드 정리
> 🔀 :: (#516) 하단 바 버튼 햅틱반응

- Tuist/Dependencies.swift
> 세미콜론 디자인 수정에 따른 버전 수정
- 1.13.3 -> 1.13.4
close #526
> 🔀 :: (#526) 세미콜론 디자인 버전 업

- Tuist/Dependencies.swift
> XWebKit 버전 업
- 1.2.4 -> 1.2.5
-
> 🔀 :: (#536) XWebKit 버전 업

- Application/Project.swift
> ios버전에 따른 위젯 안뜨는 버그 수정
- widget deploymentTarget 추가
> 🔀 :: (#532) ios버전에 따른 위젯 안뜨는 버그 수정

- Application/Sources/Scene/MealDetail/MealDetailView.swift
- Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
- Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherView.swift
> ScrollView bottom 패딩주기
- 스크롤뷰에 padding bottom 16주기
> 🔀 :: (#544) ScrollView bottom 패딩주기

- Application/Sources/Scene/Home/HomeViewModel.swift
- Application/Sources/Scene/Home/Meal/MealMenuView.swift
> 탭바 누를때마다 급식 깜빡임으로 인해 코드 삭제
- 
-
> 🔀 :: (#546) 급식 깜빡임 버그 수정

- Application/Widget/Sources/Meal/XquareMealWidget.swift
- Application/Widget/Sources/Schedule/XquareScheduleWidget.swift
- Application/Widget/Sources/TimeTable/XquareTimeTableWidget.swift
> 🔀 :: (#549) meal lock screen 아침,점심 이미지 변경

- Application/Sources/Scene/Home/HomeViewModel.swift
- Configurations/develop.xcconfig
- Configurations/product.xcconfig
- Configurations/stage.xcconfig
- Services/AuthService/Sources/Data/Remote/Response/SigninAndRefreshTokenResponse.swift
- Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
> 서버에서의 로그인 Response의 수정에 따른 대응
- 로그인 Response 수정
close #553
> 🔀 :: (#553) 로그인 Response 수정

- Application/Sources/Scene/Application/ApplicationViewModel.swift
- Application/Sources/Scene/Feed/FeedViewModel.swift
> 웹뷰 url 변경
- 웹뷰 viewModel url 변경
> 🔀 :: (#556) 웹뷰 url 변경

- Services/NotificationService/Sources/Data/Remote/Response/NotificationResponse.swift
> 🔀 :: (#564) 알림 리스트 버그 수정

- Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
- Services/AuthService/Sources/Data/Remote/Datasource/RemoteAuthDataSource.swift
- Services/AuthService/Sources/Data/Remote/Datasource/RemoteAuthDataSourceImpl.swift
- Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
> 로그아웃시 디바이스 토큰을 지우기 위해 서버에게 로그아웃 API 호출
- 로그아웃 API 추가
- 로그아웃 기능구현
- 로그아웃시 로그아웃 API 호출 디바이스 토큰이 지워짐
close #570
> 🔀 :: (#570) 로그아웃 기능 추가

- Application/Widget/Sources/Meal/XquareMealWidget.swift
- Services/MealDataService/Sources/Domain/Enum/MealTime.swift
> 홈화면 보라색 강조 위젯와 동일시
- 홈화면 보라색 강조 점심에서 저녁 넘어가는 시간 1시 -> 2시
-
> 🔀 :: (#572) 홈화면 보라색 강조 위젯와 동일시

- Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
> 급식 포커싱이 안되는 버그 수정
- .suffix로 day를 잘 가져오도록 수정
> 🔀 :: (#574) 급식 포커싱 버그 수정

- Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherViewModel.swift
> 자습감독선생 포커싱 오류 수정
-  자습감독선생 포커싱 하는 로직 수정함
> 🔀 :: (#576) 자습감독선생님 포커싱 오류 수정
